version: 3

includes:
  docker:
    taskfile: ./docker/Taskfile.yml
    dir: ./docker

vars:
  PROJ_DIR: { sh: pwd }
  SOURCE_FOLDER: ./demo_dagster/
  DEFAULT_CONFIG_FILE: "{{.SOURCE_FOLDER}}/run_config.yaml"
  DEFAULT_FILE: hello_dagster.py
  VENV_CONTEXT: poetry run

env:
  DAGSTER_HOME: "{{.PROJ_DIR}}/dagster_home"

tasks:
  setup:
    cmds:
      - poetry config virtualenvs.prefer-active-python true
      - poetry install
      - test ! -d ./dagster_home && mkdir ./dagster_home
  run: poetry run {{.CLI_ARGS}}
  cmd: poetry run python3 ./sre_helper_scripts/main.py {{.CLI_ARGS}}
  shell:
    cmds:
      - poetry shell
    interactive: true
  add: poetry add {{.CLI_ARGS}}
  dev:
    cmds:
      - "{{.VENV_CONTEXT}} dagster dev"
  dagit: "{{.VENV_CONTEXT}} dagit -f {{.SOURCE_FOLDER}}{{.FILE | default .DEFAULT_FILE}}"
  build:
    cmds:
      - docker build . -f ./docker/Dockerfile -t docker_user_code
  compose:
    dir: docker
    cmds:
      - docker compose up --build
  update:
    dir: docker
    cmds:
      - docker compose up --build --force-recreate --no-deps -d docker_user_code