version: "2.4"

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdatabase
    ports:
      - "3306:3306"
    networks:
      - dagster-backend
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/initdb.d:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    networks:
      - dagster-backend
    environment:
      - PMA_ARBITRARY=1

networks:
  dagster-backend:

volumes:
  mysql-data:
